// Generated by scripts/generate-asc-registry-owner.mjs from package-lock.json.
// Do not edit by hand. A lock bump is the pin bump: rerun the generator.

export const GOVERNED_RUNTIME_ASC_REGISTRY_OWNER = {
  consumer: "packages/pi-society-orchestrator",
  name: "@tryinget/pi-autonomous-session-control",
  version: "0.7.0",
  selector: "^0.7.0",
  url: "https://registry.npmjs.org/@tryinget/pi-autonomous-session-control/-/pi-autonomous-session-control-0.7.0.tgz",
  integrity:
    "sha512-hd7gQYjILAM2oaVbY4Ht9SzuXDtnhim/LQc2YoxfjcuQ5Ale776tbYeWHzj2NNUvbo5GzbfPgN2YQWgK7CqSLg==",
  specifiers: [
    "@tryinget/pi-autonomous-session-control/execution",
    "@tryinget/pi-autonomous-session-control",
  ],
} as const;
