// GENERATED by scripts/sync-prompt-vault-contract.mjs — do not edit.
// Source owner: core/prompt-vault/schema/client-compatibility.json

export const PROMPT_VAULT_CLIENT_CONTRACT = {
  schema_version: 13,
  minimum_supported_schema_version: 9,
  maximum_tested_schema_version: 13,
  compatibility_epoch: 1,
  compatibility_epoch_introduced_schema_version: 13,
  analytics_schema_version: 1,
  required_columns: {
    prompt_templates: [
      "artifact_kind",
      "control_mode",
      "formalization_level",
      "owner_company",
      "visibility_companies",
      "controlled_vocabulary",
      "export_to_pi",
      "version",
    ],
    executions: [
      "id",
      "entity_type",
      "entity_id",
      "entity_version",
      "input_context",
      "model",
      "output_capture_mode",
      "output_text",
      "success",
    ],
    feedback: ["execution_id", "rating", "notes", "issues"],
  },
} as const;

export const MIN_SUPPORTED_SCHEMA_VERSION =
  PROMPT_VAULT_CLIENT_CONTRACT.minimum_supported_schema_version;
export const MAX_TESTED_SCHEMA_VERSION = PROMPT_VAULT_CLIENT_CONTRACT.maximum_tested_schema_version;
export const SUPPORTED_COMPATIBILITY_EPOCH = PROMPT_VAULT_CLIENT_CONTRACT.compatibility_epoch;
export const COMPATIBILITY_EPOCH_INTRODUCED_SCHEMA_VERSION =
  PROMPT_VAULT_CLIENT_CONTRACT.compatibility_epoch_introduced_schema_version;
export const ANALYTICS_SCHEMA_VERSION = PROMPT_VAULT_CLIENT_CONTRACT.analytics_schema_version;
export const ANALYTICS_SCHEMA_SQL =
  "-- Prompt Vault retrieval analytics sidecar schema v1\n-- Machine-local append-only telemetry; deliberately outside Dolt history.\nPRAGMA journal_mode = WAL;\nPRAGMA busy_timeout = 5000;\n\nCREATE TABLE IF NOT EXISTS retrieval_events (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    entity_type TEXT NOT NULL DEFAULT 'template'\n        CHECK (entity_type IN ('template', 'skill')),\n    entity_id INTEGER NOT NULL,\n    entity_version INTEGER,\n    tool TEXT NOT NULL CHECK (tool IN ('vault_query', 'vault_retrieve', 'other')),\n    query_context TEXT,\n    selected_rank INTEGER,\n    result_count INTEGER,\n    company TEXT,\n    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\n\nCREATE INDEX IF NOT EXISTS idx_re_events_entity\n    ON retrieval_events(entity_type, entity_id);\nCREATE INDEX IF NOT EXISTS idx_re_events_created\n    ON retrieval_events(created_at);\n\nCREATE VIEW IF NOT EXISTS v_retrievals_daily AS\n    SELECT date(created_at) AS day,\n           entity_type, entity_id, COALESCE(company, '') AS company, tool,\n           COUNT(*) AS retrieval_count,\n           ROUND(AVG(selected_rank), 2) AS avg_rank,\n           MAX(result_count) AS last_result_count\n    FROM retrieval_events\n    GROUP BY day, entity_type, entity_id, COALESCE(company, ''), tool;\n\nCREATE VIEW IF NOT EXISTS v_retrievals_by_entity AS\n    SELECT entity_type, entity_id, COALESCE(company, '') AS company,\n           COUNT(*) AS retrieval_count,\n           ROUND(AVG(selected_rank), 2) AS avg_rank,\n           SUM(CASE WHEN selected_rank = 1 THEN 1 ELSE 0 END) AS top_rank_count,\n           MAX(created_at) AS last_retrieved_at\n    FROM retrieval_events\n    GROUP BY entity_type, entity_id, COALESCE(company, '');\n\nPRAGMA user_version = 1;\n";
export const REQUIRED_PROMPT_TEMPLATE_COLUMNS = [
  "artifact_kind",
  "control_mode",
  "formalization_level",
  "owner_company",
  "visibility_companies",
  "controlled_vocabulary",
  "export_to_pi",
  "version",
] as const;
export const REQUIRED_EXECUTION_COLUMNS = [
  "id",
  "entity_type",
  "entity_id",
  "entity_version",
  "input_context",
  "model",
  "output_capture_mode",
  "output_text",
  "success",
] as const;
export const REQUIRED_FEEDBACK_COLUMNS = ["execution_id", "rating", "notes", "issues"] as const;
