// DESIGN.md: inked atlas geometry is non-numeric; existing paper/ink tokens only.
export const ATLAS_CSS = `
[hidden]{display:none!important}
button,input,select{font:inherit;color:var(--colors-primary);max-width:100%}
button,select,input[type=search]{background:var(--colors-surface);border:1px solid var(--colors-primary);border-radius:var(--rounded-sm);min-height:44px;padding:var(--spacing-sm) var(--spacing-md)}
button,select,input[type=checkbox]{cursor:pointer}button:hover{background:var(--colors-neutral)}
input[type=checkbox]{width:20px;height:20px;accent-color:var(--colors-accent);flex-shrink:0}
.atlas{margin:var(--spacing-lg) 0 var(--spacing-xl);border-top:3px solid var(--colors-primary)}
.atlas-heading{display:flex;justify-content:space-between;align-items:end;gap:var(--spacing-xl);padding:var(--spacing-lg) 0}
.atlas-heading h2{font-size:clamp(32px,4.5vw,56px);letter-spacing:-.025em;margin:0}.atlas-heading h2 em{color:var(--colors-accent)}
.atlas-heading>.caption{max-width:36ch;margin:0}.atlas-toolbar{display:flex;gap:var(--spacing-md);align-items:end;flex-wrap:wrap;padding:var(--spacing-md) 0;border-top:1px solid var(--colors-muted)}
.atlas-toolbar label{display:grid;gap:var(--spacing-xs);font-size:14px}.atlas-toolbar label:first-child{flex:1;min-width:160px}.atlas-toolbar input{width:100%}
.atlas-legend{display:flex;gap:var(--spacing-md);flex-wrap:wrap;padding:var(--spacing-md) 0;font:12px/1.5 var(--typography-label-font-family)}
.signal{color:var(--colors-success)}.unknown{color:var(--colors-warning)}
.atlas-workspace{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(0,1fr);gap:var(--spacing-lg);align-items:start}
.atlas-map{max-height:80vh;overflow:auto;scrollbar-gutter:stable;min-width:0;border:1px solid var(--colors-muted);background:var(--colors-surface);padding:var(--spacing-lg)}
.atlas-island+ .atlas-island{border-top:2px solid var(--colors-primary);margin-top:var(--spacing-xl);padding-top:var(--spacing-lg)}
.atlas-island>header{display:flex;gap:var(--spacing-md);align-items:center}.atlas-island h3{font:14px/1.5 var(--typography-label-font-family);margin:0}.atlas-root{font-size:40px;line-height:1;flex-shrink:0}
.atlas-cells,.atlas-lanes{list-style:none;margin:0;padding:0}.atlas-cells{margin-left:19px;border-left:1px solid var(--colors-primary);padding:var(--spacing-lg) 0 var(--spacing-xs) var(--spacing-lg)}
.atlas-cell{position:relative;margin-bottom:var(--spacing-lg);min-width:0}.atlas-cell:last-child{margin-bottom:0}.atlas-cell:before{content:"";position:absolute;left:-24px;top:32px;width:24px;border-top:1px solid var(--colors-primary)}
.atlas-cell-heading{display:flex;align-items:stretch;gap:var(--spacing-sm)}.atlas-index{font:12px/1.5 var(--typography-label-font-family);padding-top:var(--spacing-lg);color:var(--colors-secondary)}
.atlas-node{display:flex;flex-direction:column;gap:var(--spacing-xs);flex:1;min-width:0;text-decoration:none;border:1px solid var(--colors-muted);padding:var(--spacing-md);color:var(--colors-primary);background:var(--colors-neutral);transition:border-color .15s ease}
.atlas-node .eyebrow{font-size:10px;margin:0}.atlas-node strong{font:400 24px/1.2 var(--typography-display-font-family);overflow-wrap:anywhere}.atlas-node:hover,.atlas-node[aria-current]{border-color:var(--colors-accent);box-shadow:inset 3px 0 var(--colors-accent)}
.atlas-lanes{border-left:1px dashed var(--colors-muted);margin:var(--spacing-sm) 0 0 var(--spacing-xl);padding-left:var(--spacing-md)}.atlas-lanes>li{position:relative;margin:var(--spacing-md) 0}.atlas-lanes>li:before{content:"";position:absolute;left:-16px;top:10px;width:12px;border-top:1px dashed var(--colors-muted)}
.atlas-lane-label{font:12px/1.5 var(--typography-label-font-family);overflow-wrap:anywhere}.atlas-attempts{display:flex;flex-wrap:wrap;gap:var(--spacing-sm);margin-top:var(--spacing-sm)}
.atlas-mark{display:flex;align-items:center;gap:var(--spacing-sm);min-height:44px;min-width:44px;text-decoration:none;padding:var(--spacing-xs) var(--spacing-sm);border:1px solid currentColor;border-radius:var(--rounded-sm);max-width:100%}.atlas-mark>span:first-child{font:26px/1 var(--typography-display-font-family)}.atlas-mark-label{font:11px/1.5 var(--typography-label-font-family);overflow-wrap:anywhere}.atlas-mark:hover,.atlas-mark:focus-visible{background:var(--colors-neutral)}
.atlas-pick{display:flex;align-items:center;gap:var(--spacing-sm);font-size:14px;min-height:44px;margin-left:var(--spacing-xl);cursor:pointer}.atlas-unobserved{font-size:14px;color:var(--colors-secondary)}
.atlas-inspector{position:sticky;top:var(--spacing-md);border-top:3px solid var(--colors-accent);padding:var(--spacing-md);background:var(--colors-surface);max-height:85vh;overflow:auto;scrollbar-gutter:stable}
.atlas-inspector-heading{margin-bottom:var(--spacing-lg)}.atlas-inspector-heading .eyebrow{color:var(--colors-accent);margin-bottom:var(--spacing-sm)}.atlas-panel h3{font-size:28px}.atlas-panel>.detail-body{padding:0 0 var(--spacing-md)}.atlas-panel .eyebrow{font-size:11px}.atlas-panel section{margin-bottom:var(--spacing-lg)}.atlas-raw{font:13px/1.6 var(--typography-label-font-family);padding:var(--spacing-sm);border-left:3px solid var(--colors-warning)}
.atlas-empty{padding:var(--spacing-xl) var(--spacing-md);max-width:52ch;margin:auto}.atlas-empty-symbol{font:96px/1 var(--typography-display-font-family);display:block;color:var(--colors-muted);margin-bottom:var(--spacing-lg)}.atlas-empty h3{font-size:32px}
.atlas-contributions{display:grid;grid-template-columns:1fr 1fr;gap:var(--spacing-xl);border-top:1px solid var(--colors-primary);border-bottom:1px solid var(--colors-primary);padding:var(--spacing-lg) 0;margin-top:var(--spacing-lg)}.atlas-contributions h3{margin-bottom:var(--spacing-sm)}.atlas-contributions .caption{margin:0}
.atlas-tally{display:flex;justify-content:space-between;gap:var(--spacing-md)}.atlas-tally>div{display:flex;flex-direction:column;flex:1;border-top:3px solid currentColor;padding-top:var(--spacing-sm)}.atlas-tally strong{font:48px/1.2 var(--typography-display-font-family)}.atlas-tally span{font:12px/1.5 var(--typography-label-font-family)}
.atlas-stack{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.5fr);gap:var(--spacing-xl);padding:var(--spacing-xl) var(--spacing-lg);background:var(--colors-primary);color:var(--colors-neutral);margin-top:var(--spacing-xl)}.atlas-stack h2{font-size:clamp(32px,4vw,48px)}.atlas-stack .caption{color:var(--colors-muted)}.atlas-stack .empty{color:var(--colors-neutral)}.atlas-stack .eyebrow{color:var(--colors-muted)}.atlas-compatibility{font:24px/1.3 var(--typography-display-font-family);border-top:1px solid var(--colors-muted);padding-top:var(--spacing-md)}
.stack-pair-controls{display:grid;grid-template-columns:1fr 1fr;gap:var(--spacing-md);margin-bottom:var(--spacing-md)}.stack-pair-controls label{display:grid;gap:var(--spacing-xs);font-size:14px;min-width:0}.stack-pair-controls select{width:100%}.stack-fact{border-top:1px solid var(--colors-secondary);padding:var(--spacing-md) 0}.stack-fact p{font-size:14px;margin:var(--spacing-sm) 0}.stack-boundary{padding:var(--spacing-md) 0;margin:0;font-weight:600}.atlas-stack :focus-visible{outline-color:var(--colors-neutral)}.atlas-stack button{margin-bottom:var(--spacing-md)}
.masthead{display:grid;grid-template-columns:1fr 1fr;column-gap:var(--spacing-xl)}.masthead-top{grid-column:1/-1;margin-bottom:var(--spacing-md)}.masthead h1{font-size:clamp(40px,4.5vw,56px)}.masthead .identities{margin:0}.masthead .freshness{grid-column:1/-1;margin:var(--spacing-md) 0 0}.masthead .freshness p{margin:0}.masthead .freshness p:last-child{font-size:12px}.watch{font-size:14px}.level-guide{margin-top:var(--spacing-xl)}
@media(max-width:900px){.atlas-workspace,.atlas-stack{grid-template-columns:1fr}.atlas-inspector{position:static;max-height:none}.atlas-map{max-height:70vh}.atlas-heading{align-items:start}.atlas-stack{gap:var(--spacing-lg)}}
@media(max-width:600px){.masthead,.atlas-contributions{display:block}.masthead .identities{margin-top:var(--spacing-md)}.atlas-heading{display:block}.atlas-heading>.caption{margin-top:var(--spacing-md)}.atlas-map{padding:var(--spacing-md) var(--spacing-sm)}.atlas-cells{margin-left:12px;padding-left:var(--spacing-md)}.atlas-cell:before{left:-16px;width:16px}.atlas-index{display:none}.atlas-lanes,.atlas-pick{margin-left:var(--spacing-md)}.atlas-toolbar{align-items:stretch}.atlas-toolbar label{flex:1;min-width:140px}.atlas-tally{margin-top:var(--spacing-lg)}.atlas-stack{padding:var(--spacing-lg) var(--spacing-md)}.stack-pair-controls{grid-template-columns:1fr}.atlas-node strong{font-size:22px}}
@media(prefers-reduced-motion:reduce){.atlas-node{transition:none}}
@media print{.atlas-inspector{position:static;max-height:none}.atlas-map{max-height:none;overflow:visible}.atlas-toolbar,.atlas-pick{display:none}.atlas-workspace{display:block}}
`;
