// Compact dark performance instrument; DESIGN.md owns the palette and hierarchy.
export const PERFORMANCE_CSS = `
:root{color-scheme:dark;--colors-primary:#E7ECEF;--colors-secondary:#9BA8B2;--colors-neutral:#0C1015;--colors-surface:#171D23;--colors-muted:#303841;--colors-success:#4ADE80;--colors-warning:#F4BC45;--colors-error:#F07878;--colors-accent:#7BACFF;--typography-display-font-family:"Aptos","Candara","Trebuchet MS",sans-serif}
[hidden]{display:none!important}body{font-size:14px;line-height:1.5}.page{padding-top:20px}
h1{font-size:22px;line-height:1.2;letter-spacing:0;font-weight:600}h2{font-size:18px;font-weight:600}h3{font-size:16px;font-weight:600}h4{font-size:14px}
.masthead{border:0;padding:0;display:flex;gap:12px;align-items:baseline;justify-content:space-between;flex-wrap:wrap}.masthead h1{margin:0;font-size:22px}.masthead .repo{margin:0;max-width:70ch}.masthead nav{gap:12px}.masthead nav a{min-height:44px;display:inline-flex;align-items:center}.watch{margin:0 0 12px;gap:8px}.watch .caption{font-size:12px;flex:1;min-width:200px}.watch button{font-size:12px;padding:6px 10px;border-color:var(--colors-muted)}
.perf-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:12px}.perf-toolbar h2{margin:0}.perf-controls{display:flex;gap:12px;flex:1;justify-content:flex-end;min-width:0}.perf-controls label{display:flex;align-items:center;gap:8px;min-width:0;font-size:12px;color:var(--colors-secondary)}.perf-controls label:first-child{flex:1;max-width:720px}
select,button,input{color:var(--colors-primary);background:var(--colors-surface);font:inherit;border:1px solid var(--colors-muted);border-radius:4px;min-height:44px}select{padding:6px 10px;max-width:100%;min-width:0}.perf-controls select{width:100%}.perf-controls label:last-child{flex-shrink:0}.perf-controls select:disabled{opacity:.65}
.perf-scope-title{font-size:12px;color:var(--colors-secondary);font-weight:400;margin:0 0 12px;overflow-wrap:anywhere}.perf-stats{display:grid;grid-template-columns:1.5fr 1.2fr .7fr .9fr;gap:12px;margin-bottom:16px}.perf-stats>div{background:var(--colors-surface);border:1px solid var(--colors-muted);border-radius:6px;padding:14px 16px;min-width:0}.perf-stats span{display:block;color:var(--colors-secondary);font-size:12px}.perf-stats strong{display:block;font:600 clamp(20px,2.1vw,28px)/1.5 var(--typography-label-font-family);margin:4px 0}.perf-stats strong span{display:inline;font:inherit;font-size:.75em}.perf-stats small{display:block;font-size:11px;line-height:1.4}
.perf-chart-card{background:var(--colors-surface);border:1px solid var(--colors-muted);border-radius:6px;padding:14px 16px 8px;margin-bottom:16px}.perf-chart-heading{display:flex;align-items:baseline;justify-content:space-between;gap:8px}.perf-chart-heading h3{margin:0}.perf-badge{font-size:12px;color:var(--colors-secondary);margin:4px 0 0}.perf-chart{display:block;width:100%;height:320px;overflow:visible}.perf-chart text{fill:var(--colors-secondary);font:12px var(--typography-label-font-family)}.perf-grid{stroke:var(--colors-muted);stroke-width:1;stroke-dasharray:3 5}.perf-line{fill:none;stroke:var(--colors-accent);stroke-width:2.5}.perf-area{fill:var(--colors-success);opacity:.055}.perf-dot{fill:var(--colors-accent);stroke:var(--colors-surface);stroke-width:2}.perf-hit{fill:transparent;pointer-events:all}.perf-discard{color:var(--colors-warning)}.perf-dot.perf-discard{fill:var(--colors-warning)}.perf-best{color:var(--colors-success)}.perf-dot.perf-best{fill:var(--colors-success)}.perf-failure{color:var(--colors-error)}.perf-run{color:var(--colors-primary)}.perf-chart a[aria-current="true"] .perf-dot{stroke:var(--colors-primary);stroke-width:3;r:7}.perf-chart a:focus-visible{outline:3px solid var(--colors-accent)}.perf-legend{font-size:11px;margin:0}.perf-empty-chart{height:320px;display:flex;flex-direction:column;justify-content:center;align-items:center;color:var(--colors-secondary)}.perf-empty-chart p{font-size:18px;margin:0}
.perf-table-wrap{overflow:auto;border:1px solid var(--colors-muted);border-radius:6px;background:var(--colors-surface)}.perf-table{table-layout:auto;min-width:680px;font-size:13px}.perf-table th{color:var(--colors-secondary);font-size:11px;font-weight:500}.perf-table th,.perf-table td{padding:8px 12px;vertical-align:middle}.perf-table td{padding:0 12px}.perf-table td[colspan]{padding:12px}.perf-table th:first-child{width:84px}.perf-table th:nth-child(2){width:145px}.perf-table th:nth-child(3),.perf-table th:nth-child(4){width:115px}.perf-table td:last-child{min-width:210px}.perf-outcome{display:block;font-size:11px;line-height:1.3}.perf-stats strong .perf-numeric{font:inherit;color:inherit}.perf-number{font:12px var(--typography-label-font-family);white-space:nowrap}.perf-table a{display:inline-flex;align-items:center;min-height:44px;white-space:nowrap;text-decoration:none}.perf-table tr[aria-selected="true"]{background:#202D3D;box-shadow:inset 3px 0 var(--colors-accent)}.perf-inspector{margin-top:12px;padding:12px 16px;background:var(--colors-surface);border:1px solid var(--colors-muted);border-radius:6px}.perf-inspector h3{margin-bottom:4px}.perf-inspector details{margin-top:0}.perf-inspector>details{border-top:0}.perf-inspector p{margin-bottom:6px}.perf-inspector>p:last-child{margin-bottom:0}
.exploration{margin-top:20px}.current{padding:16px 0}.current h2{font-size:22px;max-width:none}.atlas-heading h2,.atlas-stack h2{font-size:22px}.atlas-stack .empty,.atlas-stack .eyebrow{color:var(--colors-secondary)}.atlas-section{margin-top:16px}.atlas-stack{background:var(--colors-surface);color:var(--colors-primary)}.atlas-stack :focus-visible{outline-color:var(--colors-accent)}.atlas-stack input,.atlas-stack select{color:var(--colors-primary);background:var(--colors-neutral)}.atlas-stack .caption,.atlas-stack small{color:var(--colors-secondary)}.audit{padding-top:16px;margin-top:16px}footer{margin-top:20px;font-size:12px}
@media(max-width:700px){.perf-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.perf-controls{flex-wrap:wrap;justify-content:flex-start;width:100%}.perf-controls label:first-child{flex-basis:100%}.perf-toolbar{display:block}.perf-toolbar h2{margin-bottom:8px}.perf-stats strong{font-size:20px}.perf-chart-card{padding:12px 8px 8px}.masthead .repo{max-width:100%}.perf-chart-card{overflow-x:auto}.perf-chart{min-width:680px}}

/* Density refinement: existing tokens, unchanged evidence and 320px plot geometry. */
.perf-sr,.perf-toolbar:has(.perf-controls:not([hidden])) ~ [data-perf-scope] .perf-scope-title{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}
.page{padding-top:12px}.masthead{min-height:44px;align-items:center;margin-bottom:8px;gap:8px}.masthead nav{gap:12px}.masthead nav a{font-size:12px}
.perf-toolbar{display:grid;grid-template-columns:minmax(0,1fr) auto auto auto auto;align-items:center;gap:8px;margin-bottom:12px}.perf-controls,.watch{display:contents}.perf-controls label:first-child{max-width:none}.perf-controls label:last-child{width:140px}.perf-controls label{gap:6px}.watch button{padding:6px 10px;min-height:44px}.watch .caption{font-size:11px;line-height:1.3;min-width:0;max-width:130px;margin:0}#performance-notice:empty{display:none}
.perf-stats{gap:8px;margin-bottom:12px}.perf-stats>div{padding:10px 12px;overflow-wrap:anywhere}.perf-stats strong{font-size:26px;line-height:1.2;margin:4px 0}.perf-stats small{font-size:11px;line-height:1.3}.perf-chart-card{padding:10px 12px 8px;margin-bottom:12px}.perf-chart-heading{flex-wrap:wrap;row-gap:4px}.perf-chart-heading .caption{font-size:12px}.perf-chart-heading .perf-badge{flex:1;margin:0;text-align:right}.perf-badge{line-height:1.4}
@media(max-width:700px){.page{padding-top:8px}.masthead{display:flex;flex-wrap:wrap}.masthead h1{font-size:20px}.perf-toolbar{grid-template-columns:minmax(0,1fr) auto auto;gap:8px;margin-bottom:10px}.perf-controls label:first-child{grid-column:1/-1}.perf-controls label:last-child{width:auto}.watch .caption{grid-column:1/-1;max-width:none}.perf-stats{gap:8px;margin-bottom:10px}.perf-stats>div{padding:8px 10px}.perf-stats strong{font-size:20px;line-height:1.2}.perf-chart-card{padding:8px;margin-bottom:10px}.perf-chart-heading .perf-badge{flex-basis:100%;text-align:left}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto;transition:none!important;animation:none!important}}
`;
