name: Vouch Trusted Contributor Management

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  manage:
    if: github.event.label.name == 'vouch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: mitchellh/vouch/action/manage-by-issue@d66fa29a64600490892131ad87597c30c91fcac4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trustedFile: .github/ci-trusted-users.txt
          vouchLabel: vouch
