name: Vouch Pull Request Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: mitchellh/vouch/action/check-pr@d66fa29a64600490892131ad87597c30c91fcac4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trustedFile: .github/ci-trusted-users.txt
          requiredApprovals: "1"
          dismissStaleReviews: "true"
